#' Read in delimited files by accepting a vector of file paths and a vector of desired dataframe names.
#'
#' @param fp a vector of full file paths (that can be generated by list.files function).
#' @param dfNames a vector of desired dataframe names.
#' @return read-in dataframes named based on the provided dataframe names, as well as list of dataframes.

read_in_delims = function(fp, dfNames){
  list4dfs = lapply(fp, read.delim) #read in list of dfs
  names(list4dfs) = dfNames #name dataframes in list
  
  for(n in seq_along(list4dfs)){
    assign(x = names(list4dfs[n]), value = list4dfs[[n]], envir = .GlobalEnv) #extract dataframes by those names
  }
  
  assign(x = "list_of_dfs",value = list4dfs, envir = .GlobalEnv) #return list of dataframes
}