#' @author Clairessa M. Brown
#' 
#' Read in delimited files by accepting a vector of file paths and a vector of desired dataframe names.
#' 
#' @param fp a vector of full file paths (that can be generated by list.files function).
#' @param dfNames a vector of desired dataframe names.
#' @param print_dfs_to_global_envir a boolean value deciding if dataframes should be printed to global environment
#' @param list_name character string that will be the variable name of the list printed to global environment
#' @param fast a boolean value that decides whether will use data.table::fread (TRUE) or read.delim (FALSE)
#' 
#' @return user-named dataframes printed to the local environment individually as variables with a list of named dataframes, or exclusively in a list.


read_in_multiple_delims = function(fps, dfNames, print_dfs_to_global_envir=FALSE, list_name=NULL, fast = FALSE){
  if(fast == TRUE){
    library(data.table)
    list4dfs = lapply(fps, fread) # read in list of dfs
    names(list4dfs) = dfNames # name dataframes in list
  } else{
    list4dfs = lapply(fps, read.delim) # read in list of dfs
    names(list4dfs) = dfNames # name dataframes in list
  }
  
  
  if(print_dfs_to_global_envir == TRUE){
    for(n in seq_along(list4dfs)){
      assign(x = names(list4dfs[n]), value = list4dfs[[n]], envir = .GlobalEnv) 
    } 
  } else{
    for(n in seq_along(list4dfs)){
      assign(x = names(list4dfs[n]), value = list4dfs[[n]])
    }
  }
  list4dfs
}